config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, expect: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

   before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      @user = User.find(current_user.id)
      @users = User.all
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = User.find(@book.user_id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
  <div class="form">
    <%= form_with model: book, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <h2 class="text-danger">
          <%= @book.errors.count %>error prohibited this obj from being saved:
        </h2>
        <ul class="text-danger">
          <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
         <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
        <% end %>
      </div>
      <p>
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="text-danger">
    <% if @book.errors.any? %>
      <h3>
        <%= @book.errors.count %>error prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
    <%= render "users/info", user: @user %>
    <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1 ">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user_id) do%>
                    <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %>
                  <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size: "100x100", format: "jpeg", fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block btn-sm" href="/users/<%= @user.id %>/edit">
          <i class="fas fa-user-cog"></i>
        </a>
      </div>
      <%= render "books/form", book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1 ">
      <h2>Book detail</h2>
      <% if @book.user == current_user %>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, size: "100", format: "jpeg", fallback: "no_image.jpg" %><br><%= @user.name %>
                <% end %>
              </td>
              <td><%=link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          </tbody>
        </table>
      <% else %>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %><br><%= @user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@user) %></td>
              <td><%= @book.body %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>!
      </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book">Bookers !!</i></h1>
		  <p>In <i class="fas fa-book">Bookers</i></p>
		  <p>you can share and exchange  your opinions , inpressions , and emotions</p>
		  <p> about various books!</p>
		    <div class="btn-wrapper col-10 mx-auto">
		      <div class="row">
		        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
		    		<a class="btn btn-success btn-sm btn-block mb-3 sign_up" href="/users/sign_up">Sign Up</a>
		    	</div>
		  	</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/a2eb054331.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li><%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light " %></li>
              <li><%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %></li>
              <li><%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %></li>
              <% else %>
              <li><%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %></li>
              <li><%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %></li>
              <li><%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <% if notice %>
      <p class="text-success"><%= notice %></p>
　    <% end %>
　    <% if alert%>
      <p class="text-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    <main>

     <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto" >
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, size: "100x100", format: "jpeg", fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a class="btn btn-outline-secondary btn-block btn-sm" href="/users/<%= current_user.id %>/edit">
      <i class="fas fa-user-cog"></i>
    </a>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <h2 class="text-danger">
          <%= @user.errors.count %>error prohibited this obj from being saved:
        </h2>
        <ul class="text-danger">
          <% @user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
         <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :profile_image, "image" %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, "introduction" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1 ">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size: "100x100", format: "jpeg", fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block btn-sm" href="/users/<%= @user.id %>/edit">
          <i class="fas fa-user-cog"></i>
        </a>
      </div>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1 ">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do%>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", format: "jpeg", fallback: "no_image.jpg" %></td>
              <% end %>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>